# Generated by Django 5.2.1 on 2025-05-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projeto', models.CharField(blank=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Projeto')),
                ('horas_alocacao_gerente', models.PositiveIntegerField(default=0, verbose_name='Horas de Alocação do Gerente')),
                ('data_inicio', models.DateField(verbose_name='Data início contrato')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data fim contrato')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='users.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('pendente', 'Pendente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=15)),
                ('atribuido_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='users.cliente')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='dashboard.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='dashboard.projeto')),
            ],
        ),
    ]
